# Generated by Django 6.0.2 on 2026-02-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Full problem description shown to students."
                    ),
                ),
                (
                    "grading_criteria",
                    models.TextField(
                        help_text="Criteria Claude will use to evaluate submissions (e.g. correctness, edge cases, style)."
                    ),
                ),
                (
                    "example_input",
                    models.TextField(
                        blank=True, help_text="Optional example input for the student."
                    ),
                ),
                (
                    "example_output",
                    models.TextField(
                        blank=True,
                        help_text="Optional expected output for the student.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("grading", "Grading"),
                            ("graded", "Graded"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, help_text="Score out of 100", null=True
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Claude's detailed feedback"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="grader.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
