# Generated by Django 6.0.2 on 2026-02-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["subject_area", "title"]},
        ),
        migrations.RenameField(
            model_name="submission",
            old_name="code",
            new_name="answer",
        ),
        migrations.AddField(
            model_name="problem",
            name="category",
            field=models.CharField(
                choices=[("coding", "Python Coding"), ("theory", "ML/AI Theory")],
                db_index=True,
                default="coding",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="subject_area",
            field=models.CharField(
                choices=[
                    ("python_basics", "Python Basics"),
                    ("numpy", "NumPy"),
                    ("pandas", "Pandas"),
                    ("matplotlib", "Matplotlib"),
                    ("seaborn", "Seaborn"),
                    ("sklearn", "Scikit-learn"),
                    ("tensorflow", "TensorFlow"),
                    ("regression", "Regression"),
                    ("trees_forests", "Trees & Forests"),
                    ("classification", "Classification & Clustering"),
                    ("neural_networks", "Neural Networks"),
                    ("generative_ai", "Generative AI for NLP"),
                ],
                db_index=True,
                default="python_basics",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="example_input",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="example_output",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="grading_criteria",
            field=models.TextField(
                help_text="Criteria Claude will use to evaluate submissions."
            ),
        ),
    ]
